version: '3.8'

services:
  codeguard-ai:
    build: .
    container_name: codeguard-ai
    ports:
      - "8000:8000" # FastAPI
      - "8501:8501" # Streamlit
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - API_URL=http://localhost:8000
    volumes:
      - ./assets:/app/assets
