apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: finagent-ops-servicemonitor
  namespace: monitoring
  labels:
    app: finagent-ops
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: finagent-ops
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
