apiVersion: v1
kind: Service
metadata:
  name: finagent-ops-clusterip-service
  labels:
    app.kubernetes.io/name: finagent-ops
    app.kubernetes.io/component: internal-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: finagent-ops
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: finagent-ops-loadbalancer-service
  labels:
    app.kubernetes.io/name: finagent-ops
    app.kubernetes.io/component: external-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: finagent-ops
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
