"""
PASHA-NEURO-RAG Sample PDF Generator
Author: Mohammad Subhan Pasha
Generates 10 realistic enterprise PDFs for testing and RAGAS evaluation.
"""

import os
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

DOC_SPECS = [
    {
        "filename": "01_enterprise_architecture.pdf",
        "title": "PASHA Enterprise System Architecture Specification",
        "content": (
            "PASHA-NEURO-RAG is an enterprise self-correcting RAG architecture engineered by Mohammad Subhan Pasha. "
            "It combines a high performance Qdrant vector database with BM25 sparse keyword retrieval. "
            "Reciprocal Rank Fusion (RRF) with k=60 merges vector similarity scores and keyword BM25 ranks. "
            "Cross-encoder reranking is performed using BAEI/bge-reranker-large and Cohere Rerank english-v3.0. "
            "The system enforces strict multi-tenant authorization and streaming low latency responses."
        )
    },
    {
        "filename": "02_self_rag_loop_protocol.pdf",
        "title": "Self-RAG Autonomous Correction Protocol",
        "content": (
            "The self-correcting RAG workflow is powered by LangGraph state machines. "
            "When a user query is received, candidate responses generated by OpenAI GPT-4o undergo self-critique. "
            "If the critique confidence score is below 0.85, the query is automatically rewritten and re-retrieved. "
            "The maximum number of self-correction loop iterations is set to 3. "
            "This iterative refinement mechanism eliminates incomplete and irrelevant responses."
        )
    },
    {
        "filename": "03_hallucination_guard_nli.pdf",
        "title": "DeBERTa-v3 Natural Language Inference Hallucination Guard",
        "content": (
            "Hallucination control is enforced by a dedicated Validator Agent utilizing DeBERTa-v3 NLI model. "
            "Every generated statement is paired as a hypothesis against the retrieved premise context. "
            "If the entailment score is below the groundedness threshold of 0.70, the system rejects the answer. "
            "In case of ungrounded generation, the system returns: 'I don't have enough info in documents'. "
            "This guarantees 0% unverified hallucinations in critical financial and legal domains."
        )
    },
    {
        "filename": "04_vector_database_qdrant_indexing.pdf",
        "title": "Qdrant Vector Database Cluster Configuration",
        "content": (
            "Qdrant vector engine manages high dimensional embeddings generated by OpenAI text-embedding-3-large. "
            "The vector space dimension is set to 3072 using cosine similarity metric. "
            "HNSW indexing is configured with m=16 and ef_construct=100 for sub-10ms query latency. "
            "Collections are partitioned by tenant namespace with payload indexing on source_type and uri metadata."
        )
    },
    {
        "filename": "05_semantic_chunking_engine.pdf",
        "title": "Embedding-Based Semantic Chunking Specification",
        "content": (
            "Fixed-size character chunking leads to split context and loss of semantic coherent boundaries. "
            "PASHA-NEURO-RAG employs embedding-based semantic sentence chunking. "
            "Document text is split into sentences, and cosine distance is calculated between consecutive embeddings. "
            "New chunks are created at semantic distance peaks or when reaching target token count of 350 tokens."
        )
    },
    {
        "filename": "06_multi_parser_ingestion_pipeline.pdf",
        "title": "Multi-Format Document Parser Specifications",
        "content": (
            "The ingestion pipeline ingests heterogenous document sources including PDF, DOCX, Web URLs, and Notion. "
            "PyPDF and PyMuPDF extract raw text and structural elements from PDF documents. "
            "Unstructured.io and BeautifulSoup clean HTML markup from web pages and Notion exports. "
            "Asynchronous ingestion workers process files in parallel with automatic deduplication."
        )
    },
    {
        "filename": "07_observability_and_metrics.pdf",
        "title": "Prometheus & LangSmith Observability Framework",
        "content": (
            "Observability is built into the core API using Prometheus fastapi instrumentator. "
            "Metrics exposed at /metrics include request count, document ingestion counts, and chat latency histograms. "
            "LangSmith integration traces LLM generation, prompt templates, and execution latency across all graph nodes. "
            "Grafana dashboards visualize golden signals in real time."
        )
    },
    {
        "filename": "08_evaluations_and_ragas.pdf",
        "title": "RAGAS Framework Quality Benchmark Protocol",
        "content": (
            "System quality is continuously evaluated using RAGAS metrics framework. "
            "Target quality metrics require Faithfulness > 0.92, Answer Relevancy > 0.88, and Context Recall > 0.90. "
            "Ground truth evaluation datasets assess system resilience against trick queries and out-of-domain prompts."
        )
    },
    {
        "filename": "09_security_and_compliance.pdf",
        "title": "Enterprise Security and Access Control Policy",
        "content": (
            "All document vectors and payloads stored in Qdrant are encrypted at rest using AES-256. "
            "Role-Based Access Control (RBAC) restricts API endpoint usage with JWT authentication. "
            "API request rate limits are set to 100 requests per minute per IP to prevent service abuse."
        )
    },
    {
        "filename": "10_disaster_recovery_slas.pdf",
        "title": "Disaster Recovery SLAs and High Availability",
        "content": (
            "The service SLA guarantees 99.95% uptime for vector search and generation endpoints. "
            "Automatic multi-region database replication ensures Recovery Time Objective (RTO) under 5 minutes "
            "and Recovery Point Objective (RPO) under 30 seconds."
        )
    }
]


def generate_sample_pdfs(output_dir: str):
    os.makedirs(output_dir, exist_ok=True)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('TitleStyle', parent=styles['Heading1'], fontSize=16, leading=20, textColor='#1E293B')
    body_style = ParagraphStyle('BodyStyle', parent=styles['Normal'], fontSize=11, leading=16, textColor='#334155')

    for spec in DOC_SPECS:
        file_path = os.path.join(output_dir, spec["filename"])
        doc = SimpleDocTemplate(file_path, pagesize=letter)
        story = [
            Paragraph(spec["title"], title_style),
            Spacer(1, 12),
            Paragraph(spec["content"], body_style),
            Spacer(1, 12),
            Paragraph("<b>Author: Mohammad Subhan Pasha</b>", body_style)
        ]
        doc.build(story)
        print(f"Generated sample PDF: {file_path}")


if __name__ == "__main__":
    target_dir = os.path.join(os.path.dirname(__file__), "..", "sample_docs")
    generate_sample_pdfs(target_dir)
