from fastapi import FastAPI, HTTPException, UploadFile, File, Form, Depends
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional, Dict, Any, List
import os
import sys
import tempfile
import zipfile
import json
import io
from fastapi.responses import StreamingResponse

# Add core to path so we can import it
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from core.repo_ingestion import ingest_zip_file, ingest_github_repo, RepoIngestionError
from core.test_generator import generate_tests_for_codebase, TestGeneratorError

app = FastAPI(
    title="TestGen AI API",
    description="Enterprise QA Automation Tool API",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class GenerateTestsRequest(BaseModel):
    github_url: Optional[str] = None
    github_token: Optional[str] = None
    gemini_key: Optional[str] = None

# Using an in-memory store for generated tests for this demo
generated_tests_store: Dict[str, Any] = {}

@app.get("/")
def read_root() -> Dict[str, str]:
    return {"message": "TestGen AI API is running."}

import uuid

@app.post("/ingest_and_generate")
def ingest_and_generate(
    file: Optional[UploadFile] = File(None),
    github_url: Optional[str] = Form(None),
    github_token: Optional[str] = Form(None),
    gemini_key: Optional[str] = Form(None)
) -> Dict[str, Any]:
    """
    Ingests a codebase from a zip file or GitHub URL and generates tests.
    """
    if not file and not github_url:
        raise HTTPException(status_code=400, detail="Must provide either a zip file or a GitHub URL.")

    codebase_files = {}
    source_name = ""

    try:
        if file:
            source_name = file.filename
            with tempfile.NamedTemporaryFile(delete=False) as temp_zip:
                content = file.file.read()
                temp_zip.write(content)
                temp_zip_path = temp_zip.name

            try:
                codebase_files = ingest_zip_file(temp_zip_path)
            finally:
                os.remove(temp_zip_path)
        elif github_url:
            source_name = github_url
            codebase_files = ingest_github_repo(github_url, github_token)

        if not codebase_files:
            raise HTTPException(status_code=400, detail="No readable code files found in the repository.")

        # Generate Tests
        generated_results = generate_tests_for_codebase(codebase_files, api_key=gemini_key)

        # Store for export
        session_id = str(uuid.uuid4())
        generated_tests_store[session_id] = generated_results

        return {
            "status": "success",
            "source": source_name,
            "session_id": session_id,
            "results": generated_results
        }
    except RepoIngestionError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except TestGeneratorError as e:
        raise HTTPException(status_code=500, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred: {str(e)}")

@app.get("/export/scripts/{session_id}")
def export_scripts(session_id: str):
    if session_id not in generated_tests_store:
        raise HTTPException(status_code=404, detail="Session not found")

    results = generated_tests_store[session_id]
    scripts = results.get("test_scripts", [])
    data_files = results.get("test_data", [])

    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        for script in scripts:
            zf.writestr(f"scripts/{script['filename']}", script['content'])
        for data in data_files:
            zf.writestr(f"data/{data['filename']}", data['content'])

    zip_buffer.seek(0)
    return StreamingResponse(
        iter([zip_buffer.getvalue()]),
        media_type="application/x-zip-compressed",
        headers={"Content-Disposition": f"attachment; filename=generated_tests.zip"}
    )

@app.get("/export/jira/{session_id}")
def export_jira(session_id: str):
    if session_id not in generated_tests_store:
        raise HTTPException(status_code=404, detail="Session not found")

    results = generated_tests_store[session_id]
    test_cases = results.get("test_cases", [])

    # Format for Jira/TestRail (simplified JSON representation)
    export_data = {
        "projects": [
            {
                "name": "TestGen AI Export",
                "suites": [
                    {
                        "name": "Generated Test Suite",
                        "cases": [
                            {
                                "title": tc["title"],
                                "type": tc["type"],
                                "custom_steps": "Generated by TestGen AI"
                            } for tc in test_cases
                        ]
                    }
                ]
            }
        ]
    }

    return export_data
